/**
 * halfcheck_walk.cjs -- the greedy ("optimistic") walker on the settled
 * background, reimplemented from the definition, in two structurally different
 * ways, with block statistics.
 *
 *   node explorer/halfcheck_walk.cjs <seedK> <nDiagonals> [blockDiagonals]
 *
 * Background: the settled words S_k of rule 30's left region. In the stretch
 * k >= 87867 every word has period dividing 32, so a word is one uint32 with
 * bit (j mod 32) = S_k(j). Words are generated by the diagonal recurrence
 *   S_{k+1}(j) = S_{k-1}(j+1) xor (S_k(j) or S_{k+1}(j-1))
 * seeded from a consecutive pair recovered from the real picture by
 * halfcheck_picture.cjs -- so no branch table is used and no other script is
 * imported.
 *
 * Walker, form 1 (literal, Rosetta's): state x <= 0 at row t; read the settled
 * cell at diagonal k = t + x - 1, index j = 1 - x; if white x -= 1; t += 1.
 * Walker, form 2 (derived): on diagonal k at index j, scan S_k forward from j
 * to the first 1; the zeros are advances, the 1 is one stall, and the walk
 * continues on S_{k+1} at that same index. speed = advances / (advances + N).
 * The two forms must agree step for step; the script checks that.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const SEEDK = parseInt(process.argv[2] || '87868', 10);
const NDIAG = parseInt(process.argv[3] || '10000000', 10);
const BLOCK = parseInt(process.argv[4] || '1000000', 10);
const JSON_PATH = process.env.HC_JSON || path.join(__dirname, 'halfcheck_words.json');

const dump = JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));
const seed = dump.seeds.find((s) => s.k === SEEDK);
if (!seed) throw new Error(`no seed at k = ${SEEDK}; have ${dump.seeds.map((s) => s.k).join(',')}`);

/** pack a period-p (p | 32) word given as an array into a uint32, bit j = S(j) */
function pack(arr) {
  const p = arr.length;
  if (32 % p !== 0) throw new Error(`period ${p} does not divide 32`);
  let w = 0;
  for (let j = 0; j < 32; j++) if (arr[j % p]) w |= (1 << j);
  return w >>> 0;
}
const bit = (w, j) => (w >>> (j & 31)) & 1;
const rotr = (w, s) => (s === 0 ? w >>> 0 : (((w >>> s) | (w << (32 - s))) >>> 0));

/** S_{k+1} from (S_{k-1}, S_k) = (A, B). Requires B non-white. */
function nextWord(A, B) {
  if (B === 0) return null;                      // eventually-white diagonal: two solutions
  const D = rotr(A, 1);                          // D(j) = A(j+1)
  let j0 = 31 - Math.clz32(B & -B);              // some index with B(j0) = 1
  let prev = bit(D, j0) ^ 1;                     // forced: C(j0) = A(j0+1) xor 1
  let C = prev << (j0 & 31);
  for (let m = 1; m < 32; m++) {
    const j = (j0 + m) & 31;
    const v = bit(D, j) ^ (bit(B, j) | prev);
    C |= (v << j);
    prev = v;
  }
  C = C >>> 0;
  // consistency: recomputing C(j0) from C(j0-1) must reproduce the forced value
  const j = j0, jm = (j0 + 31) & 31;
  if ((bit(D, j) ^ (bit(B, j) | bit(C, jm))) !== bit(C, j)) throw new Error(`recurrence not 32-periodic at k`);
  return C;
}

/** lazy word stream: words(k) for non-decreasing k >= SEEDK */
function makeWords(k0, A0, B0) {
  let k = k0 + 1, A = A0, B = B0;                 // A = S_{k-1}, B = S_k
  return {
    get k() { return k; },
    at(kk) {
      while (k < kk) { const C = nextWord(A, B); if (C === null) throw new Error(`white diagonal at k = ${k}`); A = B; B = C; k++; }
      if (kk < k) throw new Error('word stream is forward only');
      return B;
    },
  };
}

const A0 = pack(seed.wordA), B0 = pack(seed.wordB);

// ---- validate the generated words against picture-derived spot words ------
{
  const w = makeWords(SEEDK, A0, B0);
  let checked = 0, bad = 0;
  for (const s of dump.spot) {
    if (s.k <= SEEDK + 1) continue;
    const got = w.at(s.k), want = pack(s.word);
    checked++;
    if (got !== want) { bad++; console.log(`  MISMATCH at k=${s.k}: recurrence ${got.toString(2).padStart(32, '0')} vs picture ${want.toString(2).padStart(32, '0')}`); }
  }
  console.log(`recurrence vs picture-derived words: ${checked} spot checks, ${bad} mismatches`);
}

// ---- form 1: the literal (t, x) walker ------------------------------------
function walkTX(steps, t0, x0, ckpts) {
  const w = makeWords(SEEDK, A0, B0);
  let t = t0, x = x0, adv = 0;
  const trace = [], ck = [];
  for (let n = 0; n < steps; n++) {
    const k = t + x - 1, j = 1 - x;
    const white = bit(w.at(k), j) === 0;
    if (white) { x -= 1; adv++; }
    t++;
    if (n < 2000) trace.push(white ? 1 : 0);
    if (ckpts && ckpts.includes(n + 1)) ck.push(`${n + 1}:${adv}`);
  }
  return { adv, steps, x, t, trace, ck };
}

// ---- form 2: the (k, j) scan walker ---------------------------------------
function walkKJ(nDiag, k0, j0, block) {
  const w = makeWords(SEEDK, A0, B0);
  let j = j0, adv = 0;
  const blocks = [];
  let blockAdv = 0;
  const gapHist = new Int32Array(64);
  const trace = [];
  for (let n = 0; n < nDiag; n++) {
    const B = w.at(k0 + n);
    const r = j & 31;
    const Br = rotr(B, r);
    if (Br === 0) throw new Error(`white word at k = ${k0 + n}`);
    const g = 31 - Math.clz32(Br & -Br);          // trailing zeros = gap
    adv += g; blockAdv += g;
    gapHist[Math.min(g, 63)]++;
    if (trace.length < 2000) { for (let i = 0; i < g && trace.length < 2000; i++) trace.push(1); if (trace.length < 2000) trace.push(0); }
    j += g;   // g advances move the index to the 1; the stall keeps the index and steps the diagonal
    if ((n + 1) % block === 0) { blocks.push(blockAdv / (blockAdv + block)); blockAdv = 0; }
  }
  return { adv, nDiag, steps: adv + nDiag, j, blocks, gapHist, trace };
}

// ---- cross-check the two forms --------------------------------------------
{
  // (t,x) start whose diagonal is k0 = SEEDK+2 and index j0: kappa = t+x, k = kappa-1, j = 1-x
  const j0 = 1000003;                             // arbitrary index, well inside the period lattice
  const k0 = SEEDK + 2;
  const x0 = 1 - j0, t0 = k0 + 1 - x0 + x0;       // k = t + x - 1 -> t = k + 1 - x = k + j
  const tt0 = k0 + j0;
  const a = walkTX(2000, tt0, x0);
  const b = walkKJ(400, k0, j0, 400);
  const na = a.trace.join(''), nb = b.trace.join('');
  const n = Math.min(na.length, nb.length);
  console.log(`forms agree on the first ${n} steps: ${na.slice(0, n) === nb.slice(0, n)}`);
}

// ---- same start as the picture walker, for a step-for-step comparison ------
if (SEEDK === 87868) {
  const c = walkTX(250000, 117162, -29291, [1000, 10000, 100000, 200000, 250000]);
  console.log(`settled-word walker from t0=117162 x0=-29291 (diagonal 87870, index 29292):`);
  console.log(`  advances at checkpoints (steps:advances) ${c.ck.join(' ')}`);
}

// ---- the long run ----------------------------------------------------------
const K0 = SEEDK + 2;
const J0 = parseInt(process.env.HC_J0 || String(K0 - 58578), 10);   // greedy2's own offset j - k
const t0 = Date.now();
const res = walkKJ(NDIAG, K0, J0, BLOCK);
const ms = Date.now() - t0;

const sp = res.adv / res.steps;
const bl = res.blocks;
const mean = bl.reduce((s, v) => s + v, 0) / bl.length;
const sd = Math.sqrt(bl.reduce((s, v) => s + (v - mean) * (v - mean), 0) / (bl.length - 1));
const sem = sd / Math.sqrt(bl.length);
console.log(`\nwalk on the settled background, diagonals ${K0}..${K0 + NDIAG - 1}, start index j0 = ${J0} (${ms} ms)`);
console.log(`  diagonals ${res.nDiag}, advances ${res.adv}, steps ${res.steps}`);
console.log(`  mean gap ${(res.adv / res.nDiag).toFixed(6)}  (mean gap 1 <=> speed 1/2)`);
console.log(`  speed ${sp.toFixed(7)}   excess ${(sp - 0.5).toExponential(3)}`);
console.log(`  blocks of ${BLOCK} diagonals: n=${bl.length}, mean ${mean.toFixed(7)}, sd ${sd.toExponential(3)}, sem ${sem.toExponential(3)}`);
console.log(`  (speed - 1/2) / sem = ${((sp - 0.5) / sem).toFixed(2)}`);
console.log(`  block speeds: ${bl.slice(0, 40).map((v) => v.toFixed(5)).join(' ')}`);

// cumulative speed at growing prefixes, from the block sequence
{
  let cumAdv = 0, cumDiag = 0;
  const marks = [];
  for (let i = 0; i < bl.length; i++) {
    // recover per-block advances: block speed s = a/(a+B) -> a = B s/(1-s)
    const a = BLOCK * bl[i] / (1 - bl[i]);
    cumAdv += a; cumDiag += BLOCK;
    const T = cumAdv + cumDiag;
    if ([0, 1, 3, 7, 15, 31, 63, 127, 255, bl.length - 1].includes(i)) marks.push(`T=${(T / 1e6).toFixed(1)}M: ${(cumAdv / T).toFixed(6)}`);
  }
  console.log(`  cumulative speed vs T: ${marks.join('  ')}`);
}

// gap distribution against the fair-coin law P(gap >= m) = 2^-m
{
  const tot = res.nDiag;
  let tail = tot;
  const rows = [];
  for (let m = 0; m <= 12; m++) {
    rows.push(`${m}: ${(tail / tot).toFixed(6)} vs ${(Math.pow(2, -m)).toFixed(6)}`);
    tail -= res.gapHist[m];
  }
  console.log(`  P(gap >= m) observed vs 2^-m:  ${rows.join('   ')}`);
}
