/**
 * Meridian E — how far a periodic column is from satisfying the seed's own
 * repetition clause.
 *
 * Meridian C showed the centre column is generated by the rule "choose the bit
 * that keeps the rebuilt initial row WHITE at position -k". Turn that around.
 * For ANY boundary sequence b, the same triangular recursion rebuilds an
 * initial row: column 1 from the right half-line started all white, then
 * `leftSolve` leftward. Write rowzero(b) for the resulting half-row at
 * positions -1, -2, -3, ... The map b |-> rowzero(b) is a bijection (the
 * board's crystal 40, inverted), the seed is the boundary with
 * rowzero(b) = 0^inf, and Prize 1 says no eventually periodic b has
 * rowzero(b) = 0^inf.
 *
 * So measure how badly periodic boundaries miss it: the density of black cells
 * in rowzero(b), the longest all-white prefix, and the longest white run.
 * If periodic boundaries all sit at density ~1/2 with only logarithmic white
 * runs, then the seed is at the extreme opposite end of this map and "rowzero
 * is eventually white" is a very strong demand, which is the quantitative
 * content of the clause the two precedents' proofs read.
 *
 * Nothing here proves anything.
 */

const K = 1500;

/** rowzero(b) at positions -1..-K, given b(0..K+1). */
function rowZero(b, K = b.length - 2) {
  const n = K + 2;
  // column 1 of X_b: right half-line from all white, boundary b
  const d = new Uint8Array(n);
  let half = new Uint8Array(n + 2);
  let next = new Uint8Array(n + 2);
  d[0] = 0;
  for (let t = 0; t + 1 < n; t++) {
    const m = half.length;
    next[0] = b[t] ^ (half[0] | half[1]);
    for (let x = 1; x < m - 1; x++) next[x] = half[x - 1] ^ (half[x] | half[x + 1]);
    next[m - 1] = 0;
    const tmp = half; half = next; next = tmp;
    d[t + 1] = half[0];
  }
  // leftSolve triangle: L[m][t], m + t <= K+1
  const L = [];
  for (let m = 0; m <= K + 1; m++) L.push(new Uint8Array(K + 2 - m));
  for (let t = 0; t <= K + 1; t++) L[0][t] = b[t];
  for (let t = 0; t + 1 <= K + 1; t++) L[1][t] = b[t + 1] ^ (b[t] | d[t]);
  for (let m = 2; m <= K + 1; m++) {
    for (let t = 0; t + m <= K + 1; t++) {
      L[m][t] = L[m - 1][t + 1] ^ (L[m - 1][t] | L[m - 2][t]);
    }
  }
  const out = new Uint8Array(K);
  for (let k = 1; k <= K; k++) out[k - 1] = L[k][0];
  return out;
}

function stats(label, b) {
  const r = rowZero(b);
  let ones = 0;
  for (const v of r) ones += v;
  let prefix = 0;
  while (prefix < r.length && r[prefix] === 0) prefix++;
  let longest = 0, cur = 0;
  for (const v of r) { if (v === 0) { cur++; if (cur > longest) longest = cur; } else cur = 0; }
  console.log(
    `${label}: density ${(ones / r.length).toFixed(4)}, all-white prefix ${prefix}, ` +
      `longest white run ${longest}, first 32 cells ${Array.from(r.slice(0, 32)).join('')}`,
  );
  return { prefix, longest, density: ones / r.length };
}

// the true centre column, as the positive control
function centreColumnBits(n) {
  const out = new Uint8Array(n);
  const PAD = 512;
  let pad = PAD, centre = BigInt(PAD), x = 1n << centre;
  for (let t = 0; t < n; t++) {
    out[t] = Number((x >> centre) & 1n);
    x = (x << 1n) ^ (x | (x >> 1n));
    if (--pad === 0) { x <<= BigInt(PAD); centre += BigInt(PAD); pad = PAD; }
  }
  return out;
}

const rep = (w, len = K + 2) => {
  const b = new Uint8Array(len);
  for (let i = 0; i < b.length; i++) b[i] = w[i % w.length];
  return b;
};

console.log('--- positive control ---');
stats('b = the centre column itself', centreColumnBits(K + 2));

console.log('--- periodic boundaries ---');
const words = [
  [1], [0], [1, 0], [1, 1, 0], [1, 0, 0], [1, 1, 0, 1], [1, 1, 1, 0],
  [1, 0, 1, 0, 0], [1, 1, 0, 0, 1], [1, 1, 1, 1, 1, 1, 1, 0],
  [1, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0, 1, 1, 1, 0, 0],
];
let worstPrefix = 0, worstLongest = 0;
for (const w of words) {
  const s = stats(`b = (${w.join('')})^inf`, rep(w));
  if (s.prefix > worstPrefix) worstPrefix = s.prefix;
  if (s.longest > worstLongest) worstLongest = s.longest;
}

console.log('--- a sweep over every period up to 12, at depth 300 ---');
const KS = 300;
let best = { prefix: -1 }, bestW = null;
let bestRun = { longest: -1 }, bestRunW = null;
let minDensity = 2, minW = null;
let sumDensity = 0, count = 0;
for (let p = 1; p <= 12; p++) {
  for (let v = 0; v < (1 << p); v++) {
    const w = [];
    for (let i = 0; i < p; i++) w.push((v >> (p - 1 - i)) & 1);
    if (w.every((z) => z === 0)) continue;
    const r = rowZero(rep(w, KS + 2), KS);
    let prefix = 0;
    while (prefix < r.length && r[prefix] === 0) prefix++;
    let longest = 0, cur = 0, ones = 0;
    for (const z of r) { ones += z; if (z === 0) { cur++; if (cur > longest) longest = cur; } else cur = 0; }
    const dens = ones / r.length;
    sumDensity += dens; count++;
    if (dens < minDensity) { minDensity = dens; minW = w.join(''); }
    if (prefix > best.prefix) { best = { prefix }; bestW = w.join(''); }
    if (longest > bestRun.longest) { bestRun = { longest }; bestRunW = w.join(''); }
  }
  console.log(
    `  through period ${p}: ${count} boundaries, mean density ${(sumDensity / count).toFixed(4)}, ` +
      `best all-white prefix ${best.prefix} (b = ${bestW}), longest white run ${bestRun.longest} (b = ${bestRunW}), ` +
      `min density ${minDensity.toFixed(4)} (b = ${minW})`,
  );
}

console.log('--- the same at depth 1200, for the 200 lowest-density words of period <= 12 ---');
{
  const rows = [];
  for (let p = 1; p <= 12; p++) {
    for (let v = 0; v < (1 << p); v++) {
      const w = [];
      for (let i = 0; i < p; i++) w.push((v >> (p - 1 - i)) & 1);
      if (w.every((z) => z === 0)) continue;
      const r = rowZero(rep(w, 302), 300);
      let ones = 0;
      for (const z of r) ones += z;
      rows.push([ones / r.length, w]);
    }
  }
  rows.sort((a, b2) => a[0] - b2[0]);
  let worst = 2, worstW = null;
  for (const [, w] of rows.slice(0, 200)) {
    const r = rowZero(rep(w, 1202), 1200);
    let ones = 0;
    for (const z of r) ones += z;
    const dens = ones / r.length;
    if (dens < worst) { worst = dens; worstW = w.join(''); }
  }
  console.log(`  lowest density at depth 1200 over those 200: ${worst.toFixed(4)} (b = ${worstW})`);
}
