/**
 * Meridian D — does the centre column obey either precedent's defining rule?
 *
 * Two tests, one per precedent, plus controls.
 *
 * 1. EHRENFEUCHT-MYCIELSKI. Its rule: the next bit is the COMPLEMENT of the bit
 *    that followed the most recent earlier occurrence of the longest suffix of
 *    what has been written so far that occurs earlier. Measure, for the centre
 *    column, how often the next bit is that complement. EM gives 1.000 by
 *    definition; a coin gives 0.500. Anything else is a signal.
 *    Also report the match-length distribution, which is the LZ77 statistic and
 *    is a second, independent look at whether the column repeats itself at all.
 *
 * 2. KOLAKOSKI. Its rule: the sequence of run lengths of K is K. Measure the
 *    run-length encoding of the centre column: the alphabet it needs (Kolakoski
 *    needs {1,2}), and whether any of the natural codings of the run-length
 *    sequence reproduces the column or a shift of it.
 *
 * Nothing here proves anything.
 */

const T = 1 << 19; // 524,288 terms of each sequence
const KMAX = 44;

// ---- sequences ----------------------------------------------------------

function centreColumn(n) {
  const out = new Uint8Array(n);
  const PAD = 512;
  let pad = PAD, centre = BigInt(PAD), x = 1n << centre;
  for (let t = 0; t < n; t++) {
    out[t] = Number((x >> centre) & 1n);
    x = (x << 1n) ^ (x | (x >> 1n));
    if (--pad === 0) { x <<= BigInt(PAD); centre += BigInt(PAD); pad = PAD; }
  }
  return out;
}

function xorshiftBits(n) {
  const out = new Uint8Array(n);
  let s = 0x9e3779b9 >>> 0;
  for (let i = 0; i < n; i++) {
    s ^= s << 13; s >>>= 0; s ^= s >>> 17; s ^= s << 5; s >>>= 0;
    out[i] = s & 1;
  }
  return out;
}

function thueMorse(n) {
  const out = new Uint8Array(n);
  for (let i = 0; i < n; i++) {
    let v = i, p = 0;
    while (v) { p ^= v & 1; v >>>= 1; }
    out[i] = p;
  }
  return out;
}

/** Ehrenfeucht-Mycielski, generated by its own rule with online k-gram maps. */
function ehrenfeuchtMycielski(n) {
  const out = new Uint8Array(n);
  out[0] = 0;
  const maps = [];
  const pow = [];
  for (let k = 0; k <= 40; k++) { maps.push(new Map()); pow.push(Math.pow(2, k)); }
  const keyAt = (end, k) => { // k-gram ending at index end (inclusive)
    let v = 0;
    for (let i = end - k + 1; i <= end; i++) v = v * 2 + out[i];
    return v;
  };
  for (let len = 1; len < n; len++) {
    // longest suffix of out[0..len-1] occurring earlier (search BEFORE registering)
    let best = -1, bestEnd = -1;
    for (let k = Math.min(40, len - 1); k >= 1; k--) {
      const v = keyAt(len - 1, k);
      const seen = maps[k].get(v);
      if (seen !== undefined && seen < len - 1) { best = k; bestEnd = seen; break; }
    }
    // register every k-gram ending at len-1
    for (let k = 1; k <= 40 && k <= len; k++) maps[k].set(keyAt(len - 1, k), len - 1);
    out[len] = best < 0 ? 1 : 1 - out[bestEnd + 1];
  }
  return out;
}

// ---- test 1: the EM rule ------------------------------------------------

function emTest(label, s) {
  const n = s.length;
  const bestK = new Int32Array(n).fill(-1);
  const predBit = new Int8Array(n).fill(-1);
  for (let k = 1; k <= KMAX; k++) {
    const last = new Map();
    const p = Math.pow(2, k);
    let key = 0;
    for (let i = 0; i < n; i++) {
      key = key * 2 + s[i];
      if (key >= p) key -= p;
      if (i >= k - 1) {
        const end = i; // k-gram is s[i-k+1..i]
        const seen = last.get(key);
        if (seen !== undefined && seen + 1 < n) {
          // a query at t = end+1 uses the k-gram ending at end
          if (end + 1 < n && k > bestK[end + 1]) {
            bestK[end + 1] = k;
            predBit[end + 1] = s[seen + 1];
          }
        }
        last.set(key, end);
      }
    }
  }
  let complements = 0, queries = 0;
  const hist = new Map();
  for (let t = 1; t < n; t++) {
    if (bestK[t] < 0) continue;
    queries++;
    if (s[t] !== predBit[t]) complements++;
    hist.set(bestK[t], (hist.get(bestK[t]) ?? 0) + 1);
  }
  let sum = 0, mx = 0;
  for (const [k, c] of hist) { sum += k * c; if (k > mx) mx = k; }
  console.log(
    `${label}: EM-rule agreement (next bit = complement) ${(complements / queries).toFixed(5)} ` +
      `over ${queries} queries; mean match length ${(sum / queries).toFixed(3)}, max ${mx}` +
      (mx === KMAX ? '  [saturated at KMAX]' : ''),
  );
}

// ---- test 2: the Kolakoski rule -----------------------------------------

function runs(s) {
  const out = [];
  let i = 0;
  while (i < s.length) {
    let j = i;
    while (j + 1 < s.length && s[j + 1] === s[i]) j++;
    out.push(j - i + 1);
    i = j + 1;
  }
  return out;
}

function kolakoskiTest(label, s) {
  const r = runs(s);
  let mx = 0;
  for (const v of r) if (v > mx) mx = v;
  const counts = new Map();
  for (const v of r) counts.set(v, (counts.get(v) ?? 0) + 1);
  const top = [...counts.entries()].sort((a, b) => a[0] - b[0]).slice(0, 6);
  console.log(
    `${label}: runs ${r.length}, max run ${mx}, lengths 1..6 counts ` +
      JSON.stringify(top),
  );
  // natural binary codings of the run-length sequence, compared with s itself
  const codings = {
    'len mod 2': r.map((v) => v & 1),
    'len >= 2': r.map((v) => (v >= 2 ? 1 : 0)),
    'len >= 3': r.map((v) => (v >= 3 ? 1 : 0)),
  };
  for (const [name, code] of Object.entries(codings)) {
    let bestAgree = 0.5, bestLag = 0;
    for (let lag = 0; lag < 8; lag++) {
      let agree = 0, cnt = 0;
      for (let i = 0; i + lag < code.length && i < s.length; i++) {
        if (code[i + lag] === s[i]) agree++;
        cnt++;
      }
      const rate = agree / cnt;
      if (Math.abs(rate - 0.5) > Math.abs(bestAgree - 0.5)) { bestAgree = rate; bestLag = lag; }
    }
    console.log(`   coding "${name}" vs the sequence: best agreement ${bestAgree.toFixed(4)} at lag ${bestLag}`);
  }
}

// ---- run ----------------------------------------------------------------

const c = centreColumn(T);
const x = xorshiftBits(T);
const tm = thueMorse(T);
const em = ehrenfeuchtMycielski(20000);

console.log('--- test 1: the Ehrenfeucht-Mycielski rule ---');
emTest('rule 30 centre column', c);
emTest('xorshift (null control)', x);
emTest('Thue-Morse (control)', tm);
emTest('Ehrenfeucht-Mycielski (positive control)', em);

console.log('--- test 2: the Kolakoski rule ---');
kolakoskiTest('rule 30 centre column', c);
kolakoskiTest('xorshift (null control)', x);
