// Parallax, 2026-09-13.  The GEOMETRIC analogue of the polymorphism clone.
//
// A polymorphism of the local relation is an operation g on cells commuting
// with the local function f.  The geometric analogue is an operation on whole
// CONFIGURATIONS commuting with the whole map F = rule 30 -- i.e. a cellular
// automaton in rule 30's centraliser.  Unary case first (the centraliser
// proper), then the k-ary case, which is the honest picture-level polymorphism:
// a block map G : (S^Z)^k -> S^Z with G(F x_1, ..., F x_k) = F(G(x_1,...,x_k)).
//
// Equality of two block maps of radius R is decided by all windows of length
// 2R+1, so every check below is exhaustive, not sampled.

const F = (l, c, r) => l ^ (c | r);

// ---------------------------------------------------------------- unary case
// G of radius r has a table of 2^(2r+1) bits.  G∘F = F∘G has radius r+1, so
// test every window of length 2(r+1)+1 = 2r+3.
function unaryCentraliser(r, cap = 1e7) {
  const nEntries = 1 << (2 * r + 1);
  const winLen = 2 * r + 3;
  const nWin = 1 << winLen;
  // For each window (bits w[0..winLen-1], position j has w[j + r + 1] for j in -(r+1)..(r+1))
  // build the constraint:  T[idxA] == F(T[i-1], T[i0], T[i1])
  const cons = [];
  const at = (w, j) => (w >> (j + r + 1)) & 1;   // cell j of the window
  for (let w = 0; w < nWin; w++) {
    // left side: G applied to F(w) at centre.  F(w) at cell j (|j| <= r):
    let idxA = 0;
    for (let j = -r; j <= r; j++) {
      const v = F(at(w, j - 1), at(w, j), at(w, j + 1));
      idxA |= v << (j + r);      // table index: bit (j+r) is cell j
    }
    // right side: F applied to G(w) at cells -1, 0, 1
    const idx = [];
    for (const j of [-1, 0, 1]) {
      let m = 0;
      for (let d = -r; d <= r; d++) m |= at(w, j + d) << (d + r);
      idx.push(m);
    }
    cons.push([idxA, idx[0], idx[1], idx[2]]);
  }
  // DFS over table entries with constraint checking once all four are assigned
  const T = new Int8Array(nEntries).fill(-1);
  const byMax = new Map();
  for (const c of cons) {
    const mx = Math.max(...c);
    if (!byMax.has(mx)) byMax.set(mx, []);
    byMax.get(mx).push(c);
  }
  const sols = [];
  let nodes = 0;
  function dfs(i) {
    if (sols.length > cap) return;
    if (i === nEntries) { sols.push(Array.from(T)); return; }
    for (const v of [0, 1]) {
      T[i] = v;
      nodes++;
      let ok = true;
      for (const [a, b, c, d] of (byMax.get(i) || [])) {
        if (T[a] !== F(T[b], T[c], T[d])) { ok = false; break; }
      }
      if (ok) dfs(i + 1);
    }
    T[i] = -1;
  }
  dfs(0);
  return { sols, nodes, nEntries };
}

function ruleNumberOfRadius1Table(T) {
  // table index bit (j+1) is cell j, so index m has bit2 = right? careful:
  // m |= at(w, j+d) << (d + r) with r = 1 -> d = -1 -> bit 0 is the LEFT cell.
  // Wolfram's numbering: index 4*l + 2*c + r.  So rule number bit
  // (4*l + 2*c + r) = T[ l<<0 | c<<1 | r<<2 ].
  let n = 0;
  for (let l = 0; l < 2; l++) for (let c = 0; c < 2; c++) for (let r = 0; r < 2; r++) {
    const m = l | (c << 1) | (r << 2);
    n |= T[m] << (4 * l + 2 * c + r);
  }
  return n;
}

console.log("=== [A] the unary centraliser: which CAs commute with rule 30? ===");
for (const r of [0, 1, 2, 3]) {
  const t0 = Date.now();
  const { sols, nodes, nEntries } = unaryCentraliser(r);
  const names = r === 1 ? sols.map(ruleNumberOfRadius1Table) : null;
  console.log(`  radius ${r}: ${sols.length} solutions out of 2^${nEntries} tables ` +
    `(${nodes} DFS nodes, ${Date.now() - t0} ms)`);
  if (names) console.log(`    as elementary rule numbers: [${names.sort((a, b) => a - b).join(", ")}]`);
  if (r !== 1 && sols.length <= 16) {
    console.log(`    tables: ${sols.map((T) => Array.from(T).join("")).join("  ")}`);
  }
}
console.log();
console.log("  Rule 30 is F itself; 170 and 240 are the two shifts; 204 is the identity;");
console.log("  0 is the all-white constant.  Any radius-r solution not generated by");
console.log("  {shift, F, constant 0} would be new.");
console.log();

// ------------------------------------------------------------- binary case
// G : (S^Z)^2 -> S^Z of radius r, table of 2^(2(2r+1)) bits, indexed by the
// pair of windows.  Constraint: G(Fx, Fy) = F(G(x,y)), tested on all pairs of
// windows of length 2r+3.
function binaryCentraliser(r, cap = 1e6) {
  const span = 2 * r + 1;
  const nEntries = 1 << (2 * span);   // (x-window, y-window)
  const winLen = 2 * r + 3;
  const nWin = 1 << winLen;
  const at = (w, j) => (w >> (j + r + 1)) & 1;
  const pack = (wx, wy, j) => {
    let mx = 0, my = 0;
    for (let d = -r; d <= r; d++) { mx |= at(wx, j + d) << (d + r); my |= at(wy, j + d) << (d + r); }
    return mx | (my << span);
  };
  const cons = [];
  for (let wx = 0; wx < nWin; wx++) for (let wy = 0; wy < nWin; wy++) {
    let ax = 0, ay = 0;
    for (let j = -r; j <= r; j++) {
      ax |= F(at(wx, j - 1), at(wx, j), at(wx, j + 1)) << (j + r);
      ay |= F(at(wy, j - 1), at(wy, j), at(wy, j + 1)) << (j + r);
    }
    const idxA = ax | (ay << span);
    cons.push([idxA, pack(wx, wy, -1), pack(wx, wy, 0), pack(wx, wy, 1)]);
  }
  const T = new Int8Array(nEntries).fill(-1);
  const byMax = new Map();
  for (const c of cons) {
    const mx = Math.max(...c);
    if (!byMax.has(mx)) byMax.set(mx, []);
    byMax.get(mx).push(c);
  }
  const sols = [];
  function dfs(i) {
    if (sols.length > cap) return;
    if (i === nEntries) { sols.push(Array.from(T)); return; }
    for (const v of [0, 1]) {
      T[i] = v;
      let ok = true;
      for (const [a, b, c, d] of (byMax.get(i) || [])) if (T[a] !== F(T[b], T[c], T[d])) { ok = false; break; }
      if (ok) dfs(i + 1);
    }
    T[i] = -1;
  }
  dfs(0);
  return { sols, nEntries };
}

console.log("=== [B] binary picture-level polymorphisms G(x,y) of radius r ===");
console.log("  G(Fx, Fy) = F(G(x,y)) for all configurations x, y.");
for (const r of [0, 1, 2]) {
  const t0 = Date.now();
  const { sols, nEntries } = binaryCentraliser(r);
  console.log(`  radius ${r}: ${sols.length} solutions out of 2^${nEntries} tables (${Date.now() - t0} ms)`);
  // classify: which depend on only one argument?
  const span = 2 * r + 1;
  let onlyX = 0, onlyY = 0, both = 0;
  for (const T of sols) {
    let depX = false, depY = false;
    for (let m = 0; m < nEntries; m++) {
      for (let b = 0; b < span; b++) if (T[m] !== T[m ^ (1 << b)]) depX = true;
      for (let b = span; b < 2 * span; b++) if (T[m] !== T[m ^ (1 << b)]) depY = true;
    }
    if (depX && depY) both++; else if (depX) onlyX++; else if (depY) onlyY++;
  }
  console.log(`    genuinely binary (depend on both arguments): ${both};  ` +
    `essentially unary in x: ${onlyX};  in y: ${onlyY};  constant: ${sols.length - both - onlyX - onlyY}`);
}
console.log();
console.log("  A genuinely binary picture-level polymorphism would be the geometric");
console.log("  analogue of an AND/OR/majority/minority polymorphism of the relation,");
console.log("  and would be the first structure on the space of rule 30 pictures that");
console.log("  the cell-level clone computation cannot see.");
