/**
 * Parallax / connect: the ideal generated by the rule-30 relations, and what
 * elimination actually gives.
 *
 * Over F_2, `l XOR (c OR r) = l + c + r + c*r`, so the space-time diagrams of
 * rule 30 are the zero set of the relations
 *
 *     R(t,x) :  y(t+1,x) + y(t,x-1) + y(t,x) + y(t,x+1) + y(t,x)*y(t,x+1)
 *
 * in the Boolean polynomial ring F_2[y(t,x)]/(y^2 - y). Two facts make the
 * ideal itself uninformative and are checked by hand, not here:
 *
 *   - in the "downward" order (leading term y(t+1,x)) the leading terms are
 *     PAIRWISE COPRIME distinct variables, so Buchberger's first criterion
 *     makes the generators a Groebner basis with no new element;
 *   - in the "sideways" order (leading term y(t,x-1)) the same is true, and
 *     the resulting rewrite IS the board's `leftSolve`.
 *
 * So the only elimination with content is the one that removes the interior
 * cells and keeps the column variables. In a Boolean ring every ideal is
 * radical and the ideal-variety correspondence is a bijection, so that
 * elimination ideal is exactly the vanishing ideal of the PROJECTION of the
 * variety onto the column coordinates -- i.e. of the set of realisable centre
 * column words. This script computes that set and that ideal.
 *
 * Sections
 *   A  engine check against a naive per-cell evolution
 *   B  |A(n,m)| = the number of distinct centre column words of length n+1
 *      realisable by a configuration supported in [-m, n]; the smallest m at
 *      which it saturates at 2^(n+1), i.e. at which the elimination ideal is 0
 *   C  for m = 0 (white on x <= -1, obstruction 3's class): the minimal degree
 *      of a nonzero polynomial relation satisfied by c(0..n), by rank over F_2
 *   D  the shift: is the m = 0 class forward-invariant?
 *   E  the residual's hypothesis as a linear slice: which realisable words are
 *      periodic
 */

// ---------------------------------------------------------------------------
// A cheap engine: the row is an integer, cell x at bit x + OFF. We only ever
// need the backward cone of the origin, so a row of 2n+1 cells suffices.
// ---------------------------------------------------------------------------

/** column word c(0..n) of the configuration whose cells at x = -m..n are `bits` */
function columnWord(bits, n, m) {
  // positions -n..n stored at bit p = x + n; the config is inside that range
  let row = 0;
  for (let j = 0; j <= m + n; j++) if ((bits >> j) & 1) row |= 1 << (j - m + n);
  let w = 0;
  for (let t = 0; t <= n; t++) {
    w = (w << 1) | ((row >> n) & 1);
    const l = row << 1, r = row >>> 1;
    row = (l ^ (row | r)) & 0x7fffffff;
  }
  return w;
}

function naiveColumnWord(bits, n, m) {
  const W = 4 * n + 8, O = 2 * n + 4;
  let a = new Uint8Array(W), b = new Uint8Array(W);
  for (let j = 0; j <= m + n; j++) a[O + j - m] = (bits >> j) & 1;
  let w = 0;
  for (let t = 0; t <= n; t++) {
    w = (w << 1) | a[O];
    for (let i = 1; i < W - 1; i++) b[i] = a[i - 1] ^ (a[i] | a[i + 1]);
    const tmp = a; a = b; b = tmp;
  }
  return w;
}

console.log('--- A. engine check ---');
{
  let bad = 0, tried = 0;
  for (let n = 1; n <= 8; n++) {
    for (let m = 0; m <= 4; m++) {
      for (let bits = 0; bits < (1 << (m + n + 1)); bits++) {
        tried++;
        if (columnWord(bits, n, m) !== naiveColumnWord(bits, n, m)) bad++;
      }
    }
  }
  console.log(`fast vs naive column words: ${bad} mismatches over ${tried} configurations`);
}

// ---------------------------------------------------------------------------
// Section B: how much of F_2^(n+1) is realisable?
// ---------------------------------------------------------------------------
console.log('\n--- B. |A(n,m)|: realisable column words of length n+1 ---');
console.log('    (m = how far left of the origin the configuration may be black)');
{
  const NMAX = 13, CAP = 21;   // enumerate at most 2^CAP configurations
  for (let n = 1; n <= NMAX; n++) {
    const row = [];
    let sat = null;
    for (let m = 0; m + n + 1 <= CAP && m <= n; m++) {
      const seen = new Set();
      const lim = 1 << (m + n + 1);
      for (let bits = 0; bits < lim; bits++) seen.add(columnWord(bits, n, m));
      row.push(seen.size);
      if (sat === null && seen.size === (1 << (n + 1))) sat = m;
    }
    console.log(`  n = ${String(n).padStart(2)}  2^(n+1) = ${String(1 << (n + 1)).padStart(6)}  ` +
      `|A(n,m)| for m=0.. : ${row.join(' ')}` +
      `${sat === null ? '' : `   saturates at m = ${sat}`}`);
  }
}

// ---------------------------------------------------------------------------
// Section C: the elimination ideal for m = 0
// ---------------------------------------------------------------------------
console.log('\n--- C. minimal degree of a relation on c(0..n), for the m = 0 class ---');

/** all monomials of degree <= d in v variables, as bitmasks */
function monomials(v, d) {
  const out = [];
  for (let mask = 0; mask < (1 << v); mask++) {
    let pc = 0, x = mask; while (x) { pc += x & 1; x >>= 1; }
    if (pc <= d) out.push(mask);
  }
  return out;
}

/** rank over F_2 of the |S| x |M| evaluation matrix, and the relation space dim */
function relationDim(words, v, mons) {
  // rows: one per word; columns: one per monomial. Use BigInt rows (|M| can be big)
  const rows = [];
  for (const w of words) {
    let r = 0n;
    for (let j = 0; j < mons.length; j++) {
      const mk = mons[j];
      // monomial = product of c(i) for i in mk; c(i) is bit (v-1-i) of the word
      let val = 1;
      for (let i = 0; i < v; i++) if ((mk >> i) & 1) { if (!((w >> i) & 1)) { val = 0; break; } }
      if (val) r |= 1n << BigInt(j);
    }
    rows.push(r);
  }
  // Gaussian elimination
  const pivots = [];
  let rank = 0;
  for (let r of rows) {
    for (const p of pivots) { const b = 1n << BigInt(p.col); if (r & b) r ^= p.row; }
    if (r === 0n) continue;
    let col = 0; let x = r; while (!(x & 1n)) { x >>= 1n; col++; }
    pivots.push({ col, row: r }); rank++;
  }
  return { rank, dim: mons.length - rank };
}

{
  // n <= 15 only: the row is a 31-bit int, so bit 2n must stay below 31
  for (let n = 3; n <= 15; n++) {
    const v = n + 1;
    const seen = new Set();
    for (let bits = 0; bits < (1 << (n + 1)); bits++) seen.add(columnWord(bits, n, 0));
    const words = [...seen];
    let line = `  n = ${String(n).padStart(2)}  |A| = ${String(words.length).padStart(5)}  of 2^${v}`;
    if (v <= 17) {
      for (let d = 1; d <= 3; d++) {
        const mons = monomials(v, d);
        if (mons.length > 4000) { line += `   d=${d}: skipped`; continue; }
        const { rank, dim } = relationDim(words, v, mons);
        line += `   d<=${d}: #mon ${mons.length}, rank ${rank}, relations ${dim}`;
        if (dim > 0) { line += `  <= MINIMAL DEGREE ${d}`; break; }
      }
    }
    console.log(line);
  }
}

// ---------------------------------------------------------------------------
// Section D: is the m = 0 class forward-invariant?
// ---------------------------------------------------------------------------
console.log('\n--- D. the shift ---');
{
  const n = 12;
  const A0 = new Set(), A1 = new Set();
  for (let bits = 0; bits < (1 << (n + 1)); bits++) A0.add(columnWord(bits, n, 0));
  for (let bits = 0; bits < (1 << (n + 2)); bits++) A1.add(columnWord(bits, n - 1, 1));
  // shift each length-(n+1) word to its length-n tail
  const shifted = new Set([...A0].map(w => w & ((1 << n) - 1)));
  const inside = [...shifted].filter(w => A1.has(w)).length;
  console.log(`  n = ${n}: |A(n,0)| = ${A0.size}, tails of them = ${shifted.size}, ` +
    `|A(n-1,1)| = ${A1.size}, tails inside A(n-1,1): ${inside}/${shifted.size}`);
  const B0 = new Set(); for (let b = 0; b < (1 << n); b++) B0.add(columnWord(b, n - 1, 0));
  console.log(`  tails inside A(n-1,0) (the SAME class): ` +
    `${[...shifted].filter(w => B0.has(w)).length}/${shifted.size}` +
    `   -> the m = 0 class is ${[...shifted].every(w => B0.has(w)) ? '' : 'NOT '}forward-invariant`);
}

// ---------------------------------------------------------------------------
// Section E: the linear slice
// ---------------------------------------------------------------------------
console.log('\n--- E. the residual hypothesis as a linear slice ---');
{
  for (const m of [0, 1, 2, 4]) {
    const n = Math.min(14, 20 - m);
    const seen = new Set();
    for (let bits = 0; bits < (1 << (m + n + 1)); bits++) seen.add(columnWord(bits, n, m));
    const periodic = [];
    for (let p = 1; p <= 4; p++) {
      let cnt = 0;
      for (const w of seen) {
        // c(i) is bit (n - i)... check c(i+p) = c(i) for all i with i+p <= n
        let ok = true;
        for (let i = 0; i + p <= n; i++)
          if (((w >> (n - i)) & 1) !== ((w >> (n - i - p)) & 1)) { ok = false; break; }
        if (ok) cnt++;
      }
      // how many p-periodic words of length n+1 exist at all, for the base rate
      let all = 0;
      for (let w = 0; w < (1 << (n + 1)); w++) {
        let ok = true;
        for (let i = 0; i + p <= n; i++)
          if (((w >> (n - i)) & 1) !== ((w >> (n - i - p)) & 1)) { ok = false; break; }
        if (ok) all++;
      }
      const base = (all * seen.size / (1 << (n + 1))).toFixed(2);
      periodic.push(`p=${p}: ${cnt} of ${all} (chance ${base})`);
    }
    console.log(`  m = ${m}, n = ${n}: |A| = ${seen.size}; words periodic from index 0: ` +
      periodic.join(', '));
  }
}
