// Portage, 2026-09-12. The three-state Mealy automaton E of the right edge:
//   q0 = (q0, q2),  q1 = sigma(q0, q2),  q2 = sigma(q1, q2).
// Section 0 validates the automaton against a real rule 30 triangle.
// Section A decides the group generated by {q0,q1,q2}.
// Section B computes sections and the nucleus closure.
//
// Conventions (fixed once, everything below depends on them):
//   A word is x_0 x_1 x_2 ... with x_k the cell at DEPTH k in from the right
//   edge of the row.  g = sigma^p (g|_0, g|_1) acts by g(x w) = (x ^ p) g|_x(w).
//   Products act on the left: (g h)(w) = g(h(w)), so (gh)|_x = g|_{h(x)} h|_x.

// ---------- transducers ----------
// An element is {n, perm: Uint8Array, d: Int32Array(2n), root}. State s has
// permutation bit perm[s] and sections d[2s+x].

function elt(n, perm, d, root = 0) { return { n, perm: Uint8Array.from(perm), d: Int32Array.from(d), root }; }

const ID = elt(1, [0], [0, 0]);

// Moore minimisation + BFS relabel from root: canonical form of a tree automorphism.
function canon(g) {
  // 1. reachable from root
  const seen = new Map(); const order = [];
  const stack = [g.root];
  while (stack.length) {
    const s = stack.pop();
    if (seen.has(s)) continue;
    seen.set(s, order.length); order.push(s);
    stack.push(g.d[2 * s], g.d[2 * s + 1]);
  }
  const m = order.length;
  const perm = new Uint8Array(m), d = new Int32Array(2 * m);
  for (let i = 0; i < m; i++) {
    const s = order[i];
    perm[i] = g.perm[s];
    d[2 * i] = seen.get(g.d[2 * s]);
    d[2 * i + 1] = seen.get(g.d[2 * s + 1]);
  }
  // 2. partition refinement on (perm, class(d0), class(d1))
  let cls = Array.from(perm);
  for (;;) {
    const key = new Map(); const next = new Array(m);
    for (let i = 0; i < m; i++) {
      const k = cls[i] + ',' + cls[d[2 * i]] + ',' + cls[d[2 * i + 1]];
      if (!key.has(k)) key.set(k, key.size);
      next[i] = key.get(k);
    }
    let same = true;
    for (let i = 0; i < m; i++) if (next[i] !== cls[i]) { same = false; break; }
    cls = next;
    if (same) break;
  }
  // 3. BFS relabel the quotient from the root's class
  const map = new Map(); const q = [cls[0]]; map.set(cls[0], 0);
  const P = [], D = [];
  // representative of each class
  const rep = new Map();
  for (let i = 0; i < m; i++) if (!rep.has(cls[i])) rep.set(cls[i], i);
  for (let h = 0; h < q.length; h++) {
    const c = q[h], i = rep.get(c);
    P.push(perm[i]);
    for (const x of [0, 1]) {
      const c2 = cls[d[2 * i + x]];
      if (!map.has(c2)) { map.set(c2, q.length); q.push(c2); }
      D.push(map.get(c2));
    }
  }
  return elt(q.length, P, D, 0);
}

function key(g) { return g.n + '|' + Array.from(g.perm).join('') + '|' + Array.from(g.d).join(','); }

// (g h)|_x = g|_{h(x)} h|_x ; perm of (g,h) at (s,t) is perm_g[s] ^ perm_h[t].
function mul(g, h) {
  const idx = new Map(); const order = [];
  function id(s, t) {
    const k = s * h.n + t;
    if (!idx.has(k)) { idx.set(k, order.length); order.push([s, t]); }
    return idx.get(k);
  }
  id(g.root, h.root);
  const perm = [], d = [];
  for (let i = 0; i < order.length; i++) {
    const [s, t] = order[i];
    perm.push(g.perm[s] ^ h.perm[t]);
    for (const x of [0, 1]) {
      const y = x ^ h.perm[t];              // the letter h sends x to
      d.push(id(g.d[2 * s + y], h.d[2 * t + x]));
    }
  }
  return canon(elt(order.length, perm, d, 0));
}

// inverse: same states, same perm bits, edges read by output letter.
function inv(g) {
  const perm = Array.from(g.perm), d = new Array(2 * g.n);
  for (let s = 0; s < g.n; s++) for (const y of [0, 1]) d[2 * s + y] = g.d[2 * s + (y ^ g.perm[s])];
  return canon(elt(g.n, perm, d, g.root));
}

function section(g, x) { return canon(elt(g.n, g.perm, g.d, g.d[2 * g.root + x])); }
function sectionWord(g, w) { let h = g; for (const x of w) h = section(h, x); return h; }
function isId(g) { return g.n === 1 && g.perm[0] === 0; }

// act on a word (array of bits)
function act(g, w) {
  let s = g.root; const out = [];
  for (const x of w) { out.push(x ^ g.perm[s]); s = g.d[2 * s + (x)]; }
  return out;
}

// ---------- the automaton E ----------
// states 0=q0, 1=q1, 2=q2.  q0=(q0,q2) ; q1=sigma(q0,q2) ; q2=sigma(q1,q2)
const AUT = elt(3, [0, 1, 1], [0, 2, 0, 2, 1, 2], 0);
const q0 = canon(elt(3, [0, 1, 1], [0, 2, 0, 2, 1, 2], 0));
const q1 = canon(elt(3, [0, 1, 1], [0, 2, 0, 2, 1, 2], 1));
const q2 = canon(elt(3, [0, 1, 1], [0, 2, 0, 2, 1, 2], 2));

// ---------- section 0: is this really rule 30's right edge? ----------
function rowNat(t) { let r = 1n; for (let i = 0; i < t; i++) r = (4n * r) ^ ((2n * r) | r); return r; }
function bit(x, k) { return Number((x >> BigInt(k)) & 1n); }
// T on the edge word: bit k = depth k.  T(w) = w ^ ((w<<1)|(w<<2))
function T(w, mask) { return (w ^ ((w << 1n) | (w << 2n))) & mask; }

function section0() {
  console.log('=== 0. the automaton against a real triangle ===');
  const N = 400;                      // depths kept
  const mask = (1n << BigInt(N)) - 1n;
  let w = 1n;                          // delta = 1000...
  let badEdge = 0, badCenter = 0, cells = 0;
  const center = [];
  for (let t = 0; t < N; t++) {
    const r = rowNat(t);
    // e(t)_k = cell(t, t-k) = bit (2t-k) of rowNat t, for k <= 2t
    for (let k = 0; k <= Math.min(2 * t, N - 1); k++) { cells++; if (bit(w, k) !== bit(r, 2 * t - k)) badEdge++; }
    if (bit(w, t) !== bit(r, t)) badCenter++;
    center.push(bit(r, t));
    w = T(w, mask);
  }
  console.log(`  edge word vs picture: ${badEdge} mismatches over ${cells} cells`);
  console.log(`  centerColumn t = (T^t delta)_t: ${badCenter} mismatches over ${N} rows`);
  console.log(`  first 24 of the centre column: ${center.slice(0, 24).join('')}`);
  // the 3-state automaton reproduces T on every word of length L
  const L = 18; let badAut = 0;
  for (let v = 0; v < (1 << L); v++) {
    const wArr = []; for (let k = 0; k < L; k++) wArr.push((v >> k) & 1);
    const outA = act(q0, wArr);
    let x = 0n; for (let k = 0; k < L; k++) if (wArr[k]) x |= 1n << BigInt(k);
    const y = T(x, (1n << BigInt(L)) - 1n);
    for (let k = 0; k < L; k++) if (outA[k] !== bit(y, k)) { badAut++; break; }
  }
  console.log(`  q0 vs the bit map on all 2^${L} words: ${badAut} mismatches`);
  // mirror guard: rule 86's edge map would be w ^ ((w>>1)|(w>>2)) in these
  // coordinates and does NOT reproduce the centre column.
  let w2 = 1n, badMirror = 0;
  for (let t = 0; t < 40; t++) { if (bit(w2, t) !== bit(rowNat(t), t)) badMirror++; w2 = (w2 ^ ((w2 >> 1n) | (w2 >> 2n))) & mask; }
  console.log(`  mirror control (w ^ ((w>>1)|(w>>2))): ${badMirror} mismatches over 40 rows (want: many)`);
}

// ---------- section A: what group is <q0,q1,q2> ? ----------
function sectionA() {
  console.log('\n=== A. the group generated by the three states ===');
  const gens = [q0, q1, q2];
  const names = ['q0', 'q1', 'q2'];
  for (let i = 0; i < 3; i++) console.log(`  ${names[i]}: states=${gens[i].n} perm=${Array.from(gens[i].perm).join('')} d=${Array.from(gens[i].d).join(',')}`);
  // commutators
  for (const [i, j] of [[0, 1], [0, 2], [1, 2]]) {
    const c = mul(mul(gens[i], gens[j]), inv(mul(gens[j], gens[i])));
    console.log(`  [${names[i]},${names[j]}] trivial? ${isId(c)}  (states ${c.n})`);
  }
  // ball growth
  const all = new Map(); all.set(key(ID), ID);
  let frontier = [ID];
  const alphabet = [q0, q1, q2, inv(q0), inv(q1), inv(q2)];
  const sizes = [];
  for (let r = 1; r <= 8; r++) {
    const next = [];
    for (const g of frontier) for (const a of alphabet) {
      const p = mul(a, g); const k = key(p);
      if (!all.has(k)) { all.set(k, p); next.push(p); }
    }
    frontier = next; sizes.push(all.size);
    if (all.size > 40000) { console.log(`  ball sizes r=1..${r}: ${sizes.join(' ')} (capped)`); break; }
  }
  console.log(`  ball sizes r=1..${sizes.length}: ${sizes.join(' ')}`);
  console.log(`  growth ratios: ${sizes.slice(1).map((s, i) => (s / sizes[i]).toFixed(3)).join(' ')}`);
  return all;
}

// ---------- section B: sections, activity, nucleus closure ----------
function sectionB() {
  console.log('\n=== B. sections and the nucleus ===');
  const gens = [q0, q1, q2];
  const alphabet = [q0, q1, q2, inv(q0), inv(q1), inv(q2)];
  // ball of radius r, then all level-n sections of it
  let ball = new Map(); ball.set(key(ID), ID);
  let frontier = [ID];
  for (let r = 1; r <= 6; r++) {
    const next = [];
    for (const g of frontier) for (const a of alphabet) {
      const p = mul(a, g); const k = key(p);
      if (!ball.has(k)) { ball.set(k, p); next.push(p); }
    }
    frontier = next;
    const rows = [];
    for (let n = 1; n <= 10; n++) {
      const S = new Map();
      for (const g of ball.values()) {
        // all 2^n sections
        let layer = [g];
        for (let i = 0; i < n; i++) { const nl = []; for (const h of layer) { nl.push(section(h, 0), section(h, 1)); } layer = nl; }
        for (const h of layer) S.set(key(h), h);
      }
      rows.push(S.size);
    }
    console.log(`  |ball(${r})| = ${ball.size}; |level-n sections| n=1..10: ${rows.join(' ')}`);
  }
}

section0();
sectionA();
sectionB();
