// Sextant, 2026-09-12.  The cone condition as a Boolean function of the free
// bits, and Rowland's a(n) as a cross-check.
//
// The right-diagonal tower over a configuration white at every x >= 1 is
// generated by R_0, R_1 and the free bits R_k(0) = b_k (crystal 40: b is free).
// The backward extension then gives R_k(-k) = X_b(-k), so the cone condition
// at level k is the Boolean function
//     F_k(b_0, ..., b_k) := X_b(-k) = 0.
// Measured here: its algebraic degree and support; that it is affine in its top
// variable b_k (so it DETERMINES b_k, which is the topic's second death mode);
// how many words satisfy every condition; and how fast a random b violates it.
//
// Separately: m(2^n), the distance from row 2^n's right edge to the next black
// cell, against Rowland 2006's printed a(0..40) and against the bound n+1 that
// the kernel file sextant10_scratch_cone.lean proves.

// ------------------------------------------- X_b by the board's own recursions

// evolveHalfRight with a white row 0: H(t,k) = column X (k+1) t
// leftSolve: L(k,t) = column X (-k) t ;  F_k = L(k, 0)
function coneF(b, K, XOR = false) {
  const comb = XOR ? ((p, q) => p ^ q) : ((p, q) => p | q);
  // b has length K+1 (times 0..K)
  const W = K + 4;
  // H[t][k], t = 0..K, k = 0..W-1
  const H = [];
  H.push(new Uint8Array(W));                       // row 0 is white at x >= 1
  for (let t = 0; t < K; t++) {
    const prev = H[t], nxt = new Uint8Array(W);
    nxt[0] = b[t] ^ comb(prev[0], prev[1]);
    for (let k = 1; k < W - 1; k++) nxt[k] = prev[k - 1] ^ comb(prev[k], prev[k + 1]);
    H.push(nxt);
  }
  const col1 = (t) => H[t][0];
  // L[k][t]
  const L = [];
  L.push(Uint8Array.from(b));                                        // column 0
  {
    const l1 = new Uint8Array(K + 1);
    for (let t = 0; t + 1 <= K; t++) l1[t] = b[t + 1] ^ comb(b[t], col1(t));
    L.push(l1);
  }
  for (let k = 2; k <= K; k++) {
    const cur = new Uint8Array(K + 1);
    for (let t = 0; t + 1 <= K - k + 1; t++) cur[t] = L[k - 1][t + 1] ^ comb(L[k - 1][t], L[k - 2][t]);
    L.push(cur);
  }
  const out = new Uint8Array(K + 1);
  for (let k = 0; k <= K; k++) out[k] = L[k][0];
  return out;                                       // out[k] = X_b(-k)
}

// ------------------------------------------- validate against the real picture

const T = 600;
const rows = [];
{
  let cur = new Uint8Array(1); cur[0] = 1;
  rows.push(cur);
  for (let t = 1; t <= T; t++) {
    const p = rows[t - 1], n = new Uint8Array(p.length + 2);
    const g = (i) => (i < 0 || i >= p.length) ? 0 : p[i];
    for (let j = 0; j < n.length; j++) n[j] = g(j - 2) ^ (g(j - 1) | g(j));
    rows.push(n);
  }
}
const cell = (t, x) => { const a = rows[t], i = x + t; return (i < 0 || i >= a.length) ? 0 : a[i]; };
const cc = [];
for (let t = 0; t <= T; t++) cc.push(cell(t, 0));

{
  const K = 200;
  const F = coneF(cc.slice(0, K + 1), K);
  // for the seed, X(-k) = 0 for k >= 1 and X(0) = 1
  let bad = 0;
  for (let k = 0; k <= K; k++) if (F[k] !== (k === 0 ? 1 : 0)) bad++;
  console.log(`solver check: X_b(-k) for b = the true centre column, k = 0..${K}: ${bad} deviations from initialConfig`);
  // and a second check: a perturbed b must NOT give the seed
  const b2 = cc.slice(0, K + 1); b2[7] ^= 1;
  const F2 = coneF(b2, K);
  let first = -1; for (let k = 1; k <= K; k++) if (F2[k] !== 0) { first = k; break; }
  console.log(`             flipping b_7 makes the first violation land at k = ${first}`);
  console.log(`             (I expected > 7 and it is exactly 7 -- F_k is AFFINE in b_k, so the flip shows up at once)`);
}

// ------------------------------------------- degree and support of F_k

function anf(truth, nvars) {
  // in-place Moebius transform: truth indexed by bitmask of (b_0..b_{n-1})
  const a = Uint8Array.from(truth);
  for (let i = 0; i < nvars; i++) {
    const bit = 1 << i;
    for (let m = 0; m < a.length; m++) if (m & bit) a[m] ^= a[m ^ bit];
  }
  return a;
}

function report(label, XOR) {
console.log(`\ndegree and support of F_k as a Boolean function of b_0..b_k  [${label}]:`);
console.log('  k   vars  support   ANF density   degree   deg/k   affine in b_k?');
for (let k = 1; k <= 17; k++) {
  const nv = k + 1;
  const N = 1 << nv;
  const truth = new Uint8Array(N);
  const b = new Uint8Array(nv);
  for (let m = 0; m < N; m++) {
    for (let i = 0; i < nv; i++) b[i] = (m >> i) & 1;
    truth[m] = coneF(b, k, XOR)[k];
  }
  const A = anf(truth, nv);
  let support = 0, degree = 0, degNoTop = 0, topOK = true;
  const topBit = 1 << k;
  for (let m = 0; m < N; m++) {
    if (!A[m]) continue;
    support++;
    let pc = 0; for (let i = 0; i < nv; i++) if (m & (1 << i)) pc++;
    if (pc > degree) degree = pc;
    if (m & topBit) { if (m !== topBit) topOK = false; }
    else if (pc > degNoTop) degNoTop = pc;
  }
  const hasTop = A[topBit] === 1;
  console.log(`  ${String(k).padStart(2)}   ${String(nv).padStart(4)}  ${String(support).padStart(7)}       ${(support / N).toFixed(4)}  ${String(degree).padStart(7)}   ${(degree / k).toFixed(3)}   ${(hasTop && topOK) ? 'yes' : 'NO '}  (deg w/o b_k ${degNoTop})`);
}
}
report('rule 30, OR', false);
report('OR -> XOR, crystal 66 control', true);

// ------------------------------------------- how many words satisfy them all

console.log('\nwords b in {0,1}^(K+1) with X_b(-k) = 0 for every k = 1..K:');
for (let K = 4; K <= 18; K++) {
  const N = 1 << (K + 1);
  let count = 0; const witnesses = [];
  const b = new Uint8Array(K + 1);
  for (let m = 0; m < N; m++) {
    for (let i = 0; i <= K; i++) b[i] = (m >> i) & 1;
    const F = coneF(b, K);
    let ok = true;
    for (let k = 1; k <= K; k++) if (F[k] !== 0) { ok = false; break; }
    if (ok) { count++; if (witnesses.length < 4) witnesses.push(Array.from(b).join('')); }
  }
  const truth = cc.slice(0, K + 1).join('');
  console.log(`  K = ${String(K).padStart(2)}: ${count} of ${N}   ${witnesses.join(' , ')}   (centre column prefix ${truth})`);
}

// ------------------------------------------- a random b violates it how fast?

{
  let s = 0x9e3779b9;
  const rnd = () => { s ^= s << 13; s >>>= 0; s ^= s >>> 17; s ^= s << 5; s >>>= 0; return s; };
  const K = 60, trials = 20000;
  const hist = new Array(K + 2).fill(0);
  let sum = 0, never = 0;
  for (let n = 0; n < trials; n++) {
    const b = new Uint8Array(K + 1);
    b[0] = 1;
    for (let i = 1; i <= K; i++) b[i] = rnd() & 1;
    const F = coneF(b, K);
    let first = -1;
    for (let k = 1; k <= K; k++) if (F[k] !== 0) { first = k; break; }
    if (first < 0) { never++; } else { hist[first]++; sum += first; }
  }
  console.log(`\nrandom b (b_0 = 1, ${trials} trials, K = ${K}): mean first violation level ${(sum / (trials - never)).toFixed(4)} (a coin gives 2.0000), never-violating ${never}`);
  console.log(`  histogram of the first violating level, k = 1..10: ${hist.slice(1, 11).join(' ')}   (a coin gives ${trials / 2} ${trials / 4} ${trials / 8} ...)`);
}

// ------------------------------------------- m(2^n) against Rowland's a(n)

{
  const aRow = [1, 3, 4, 6, 7, 9, 15, 16, 24, 25, 27, 29, 34, 36, 37, 39, 41, 43, 48, 49, 51,
    54, 55, 58, 60, 63, 64, 66, 69, 70, 72, 74, 77, 79, 80, 82, 84, 86, 90, 91, 93];
  let viol = 0;
  for (let n = 0; n < aRow.length; n++) if (aRow[n] < n + 1) viol++;
  console.log(`\nRowland 2006's printed a(0..40) against the proved bound a(n) >= n+1: ${viol} violations`);
  console.log(`  slack a(n) - n for n = 0..12: ${aRow.slice(0, 13).map((v, n) => v - n).join(' ')}`);

  // m(2^n) computed from the tower: least d >= 1 with R_d(2^n - d) = 1
  const NMAX = 22, KLEV = 60;
  const L = (1 << NMAX) + 8 * KLEV + 16;
  let prev2 = new Uint8Array(L), prev1 = new Uint8Array(L), spare = new Uint8Array(L);
  const hits = [];                       // hits[d] = array over n of R_d(2^n - d)
  for (let k = 0; k <= KLEV; k++) {
    let cur = spare;
    if (k === 0) cur.fill(1);
    else if (k === 1) { for (let j = 0; j < L; j++) cur[j] = (j % 2 === 0) ? 1 : 0; }
    else {
      cur[0] = cc[k];
      for (let i = 0; i + 2 < L; i++) cur[i + 1] = cur[i] ^ (prev1[i + 1] | prev2[i + 2]);
      cur[L - 1] = 0;
    }
    const row = [];
    // index 2^n - k is negative when k > 2^n (only small n); read those cells
    // out of the picture instead of assuming periodicity below index 0.
    for (let n = 0; n <= NMAX; n++) {
      const idx = (1 << n) - k;
      row.push(idx >= 0 ? cur[idx] : cell(1 << n, (1 << n) - k));
    }
    hits.push(row);
    spare = prev2; prev2 = prev1; prev1 = cur;
  }
  const mvals = [];
  for (let n = 0; n <= NMAX; n++) {
    let m = -1;
    for (let d = 1; d <= KLEV; d++) if (hits[d][n] === 1) { m = d; break; }
    mvals.push(m);
  }
  console.log(`  m(2^n) from the tower, n = 0..${NMAX}:  ${mvals.join(' ')}`);
  console.log(`  Rowland's a(n),        n = 0..${NMAX}:  ${aRow.slice(0, NMAX + 1).join(' ')}`);
  let agree = 0; for (let n = 0; n <= NMAX; n++) if (mvals[n] === aRow[n]) agree++;
  console.log(`  agree at ${agree} of ${NMAX + 1}; all >= n+1: ${mvals.every((v, n) => v >= n + 1)}`);
}
